In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/krishnaabisht09/countries-dataset/Countries.csv
/kaggle/input/datasets/abhigangwar30/anime-project/anime.csv

In [2]:
labels=['a','b','c','d']
my_list=[1,2,3,4]
arr=np.array(my_list)
d={1:10,2:20,3:30}

In [3]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
pd.Series(my_list,index=labels)

a    1
b    2
c    3
d    4
dtype: int64

# data frames

In [5]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data) # multiple series creates a dataframe
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
pd.DataFrame(data_list) # this will have no clumn name and instead it will have numbers like 0 1 2 ...
# to add columns we will use the following methods 
columns=['name','age','city','salary']  # comtains the column names
df2=pd.DataFrame(data_list,columns=columns) # now it has column names 
df2
index=['a','c','b','v'] # contains the index 
df3=pd.DataFrame(data_list,index=index,columns=columns) # has custom column and index 
df3

    name  age      city  salary
a   John   28  New York   65000
c   Anna   34     Paris   70000
b  Peter   29    Berlin   62000
v  Linda   42    London   85000

In [7]:
# extrating only a perticular column contents
names=df3['name']
names
# extracting contents of multiple columns
col=['name','salary','age']
name_sal=df3[col] # provide name with salary
name_sal

    name  salary  age
a   John   65000   28
c   Anna   70000   34
b  Peter   62000   29
v  Linda   85000   42

In [8]:
# adding a new column in the dataset 
df3['Stream']=['AI-Engineer','Data Scientist','Robotics Engineer','Full Stack Developer']
df3

    name  age      city  salary                Stream
a   John   28  New York   65000           AI-Engineer
c   Anna   34     Paris   70000        Data Scientist
b  Peter   29    Berlin   62000     Robotics Engineer
v  Linda   42    London   85000  Full Stack Developer

In [9]:
# to delete a column 
df3.drop('Stream',axis=1) # without axis it will show error 
'''
since axis=0(default)--> x-axis => it searches in the roes for the column name 
axis=1--> y-axis => searches colimn name in the columns

Note: the actual change has not yet implemented the result it showing is a sample of the action
to implement it we need to use inplace=True
'''
df3.drop('Stream',axis=1,inplace=True)
df3

    name  age      city  salary
a   John   28  New York   65000
c   Anna   34     Paris   70000
b  Peter   29    Berlin   62000
v  Linda   42    London   85000

In [10]:
# working on rows 
df.loc[[1,2]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [11]:
# setting a portion 
df.loc[[0,3]][['Name','Salary']]

    Name  Salary
0   John   65000
3  Linda   85000

In [12]:
# conditional selection
# Eg. i want to see the people whoose salary is mire than 65K
df[df['Salary']>65000]

# setting multiple conditions
df[(df['Salary']>65000) & (df['City']=='Paris')] # for multiple conditions put the conditions inside the parenthesis(Condition)

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Handling Missing values

In [13]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
# to find which cell is NA 
df.isna()
df.isna().sum() # to find which column has how many NA values
df.isna().any() # to find if any column has any NA values?
df.dropna() # this will remove the rows with NA values
# dropna() works in row wise
df.dropna(thresh=3) # thresh is for checking id it has that number of nonNA values or not


df.fillna('pong') # to fill the NA values with the set number/string.
# fillna() works in column wise
vals={'A':-1,'B':-2,"C":-3,"D":-4}
df.fillna(value=vals)
df.fillna(df.mean()) # fill with mean value of that column

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# Merging, joining , Concatination

In [15]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [16]:
print(employees)
print(salaries)

# merging 
pd.merge(employees,salaries) # merging two tables 
pd.merge(employees,salaries,on='employee_id') # setting on which column i need the merging 
pd.merge(employees,salaries,on='employee_id',how='outer') # outer join
pd.merge(employees,salaries,on='employee_id',how='right') # right join

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR
   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [17]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [18]:
pd.concat([df1,df2])
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [19]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [20]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

# Group By and Aggregation

In [21]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [22]:
cat=df.groupby(['Store','Category'])[['Sales','Quantity']].sum()
print(cat)

                Sales  Quantity
Store Category
S1    A           220        18
      B           500        40
S2    A           350        27
      B           430        38

## Aggregation
- multiple things combined and then presented

In [23]:
cat=df.groupby(['Store','Category'])[['Sales','Quantity']].sum()
cat['Mean']=df.groupby(['Store','Category'])[['Sales']].mean()
cat['std']=df.groupby(['Store','Category'])[['Sales']].std()

# instead of doing the statistical oparation manually we will use aggregation 
new_cat=cat['Sales'].agg(['sum','mean','median','max','min','count','std'])
bat=df['Sales'].agg(['sum','mean','median','max','min','count','std'])
print(cat)
print(new_cat)
print(bat)

                Sales  Quantity   Mean        std
Store Category
S1    A           220        18  110.0  14.142136
      B           500        40  250.0  70.710678
S2    A           350        27  175.0  35.355339
      B           430        38  215.0  49.497475
sum       1500.000000
mean       375.000000
median     390.000000
max        500.000000
min        220.000000
count        4.000000
std        120.138809
Name: Sales, dtype: float64
sum       1500.000000
mean       187.500000
median     190.000000
max        300.000000
min        100.000000
count        8.000000
std         66.062741
Name: Sales, dtype: float64

# Pivot Tables

In [24]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    321     34   John  January      Q1
1  2023-01-02       B   West    956     43   Mary  January      Q1
2  2023-01-03       C  North    727     58    Bob  January      Q1
3  2023-01-04       D  South    172     40  Alice  January      Q1
4  2023-01-05       A   East    448     99   John  January      Q1
5  2023-01-06       B   West    765     17   Mary  January      Q1
6  2023-01-07       C  North    783     19    Bob  January      Q1
7  2023-01-08       D  South    480     92  Alice  January      Q1
8  2023-01-09       A   East    866     97   John  January      Q1
9  2023-01-10       B   West    886     20   Mary  January      Q1
10 2023-01-11       C  North    469     20    Bob  January      Q1
11 2023-01-12       D  South    430     14  Alice  January      Q1
12 2023-01-13       A   East    681     74   John  January      Q1
13 2023-01-14       B   West    908     73   Mary  January      Q1
14 2023-01-15       C  North    254     25    Bob  January      Q1
15 2023-01-16       D  South    752     63  Alice  January      Q1
16 2023-01-17       A   East    815     69   John  January      Q1
17 2023-01-18       B   West    313     33   Mary  January      Q1
18 2023-01-19       C  North    365     98    Bob  January      Q1
19 2023-01-20       D  South    975     48  Alice  January      Q1

In [25]:
pd.pivot_table(df,values=['Sales','Units'],index='Quarter',columns="Product",aggfunc='sum')

        Sales                   Units
Product     A     B     C     D     A    B    C    D
Quarter
Q1       3131  3828  2598  2809   373  186  220  257

In [ ]:
pd.crosstab(df['Region'],df['Rep'])

# Oparations

In [ ]:
df.shape
df.columns
df.describe() # all the aggregated functions

In [ ]:
df.shape[0]

In [ ]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df

In [ ]:
df['A']*10+2
df['A'].apply(lambda x: x**3-3)
df['D']=df['A'].apply(lambda x: x**3-3)
df

# Feature Extraction

- [X] make a new column for episode count
- [X] make a new column for time stamp
- [X] which anime has the highest score
- [X] give me top 5 highest scoring anime
- [X] which anime has the highest episode count
- [X] animes with top 5 episode count
- [X] which is the longest running anime

In [ ]:
df=pd.read_csv('/kaggle/input/datasets/abhigangwar30/anime-project/anime.csv')
df.head(5)

In [ ]:
df.loc[0]

In [ ]:
# since the episode count is inside title bounded by () then i need to extract that using a function
def exct_epi(title):
    if '(' in title:
        start=title.index('(')
        if ')' in title and title.index(')')>start:
            epi_count=title[start+1:title.index(')')]
            epi_count=epi_count.split(' ')
            return int(epi_count[0])

print(exct_epi(df.loc[2]['Title']))

# extract time stamp from the title
def exct_ts(title):
    start=title.index(')')+1
    #print(start)
    ts=title[start:start+19]
    return ts

print(exct_ts(df.loc[0]['Title']))

# extract no of monthes the show is aired
mon={'Jan':1,'Feb':2,'Mar':3,'Apr':4,'May':5,'Jun':6,'Jul':7,'Aug':8,'Sep':9,'Oct':10,'Nov':11,'Dec':12}
def mon_cnt(colm):
    colm=colm.split(' - ')
    m1,y1=colm[0].split(' ')
    m2,y2=colm[1].split(' ')
    cnt=0
    if (int(y1)<int(y2)):
        cnt=int(mon[m2])+(12-int(mon[m1])+1)
    elif (int(y1)==int(y2)):
        cnt=int(mon[m2])-int(mon[m1])+1
    else:
        return "NULL"
    return cnt

print(mon_cnt(exct_ts(df.loc[0]['Title'])))

In [ ]:
df["EPISODES"]=[exct_epi(df.loc[title]['Title']) for title in range(int(df.shape[0]))]
df['Time-Stamp']=df['Title'].apply(exct_ts)
df['Months-Aired']=df['Time-Stamp'].apply(mon_cnt)
df

In [ ]:
# which anime has the highest score 
title=df[df['Score'] == df['Score'].max()]['Title']
title

In [ ]:
#top 5 highest scoring anime
df['Title'].head(5)

In [ ]:
# which anime has the highest episode count
df[df['EPISODES']== df['EPISODES'].max()][['Title','EPISODES']]

In [ ]:
# animes with top 5 episode count
df.sort_values(by='EPISODES',ascending=False)['Title'].head(5)

In [ ]:
#which is the longest running anime
df[df['Months-Aired']== df['Months-Aired'].max()]
#df.sort_values(by='Months-Aired',ascending=False)

# Project
- we will use the countries dataset

In [26]:
df=pd.read_csv('/kaggle/input/datasets/krishnaabisht09/countries-dataset/Countries.csv')
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [30]:
# data pre-processing 
# handling NA values ,missing values 

df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [ ]:
# which country has the highest population 
# what is the capital of country with highest population 
# which country has the least population 
# what is the capital of country with least population 
# give me top 5 countries with highest demographic score

In [97]:
#df.head(5)
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [36]:
# country with highest population along with its capital and population
df.sort_values(by='population',ascending=False).head(1)[['country','capital_city','population']]

   country capital_city  population
75   India    New Delhi  1417173173

In [38]:
# country with least population along with its capital and population
df.sort_values(by='population',ascending=True).head(1)[['country','capital_city','population']]

    country capital_city  population
179  Tuvalu     Funafuti       11312

In [42]:
# give me top 5 countries with highest demographic score 
df.sort_values(by='democracy_score',ascending=False).head(5)[['country','democracy_score']]

         country  democracy_score
127       Norway             9.87
74       Iceland             9.58
164       Sweden             9.39
122  New Zealand             9.26
46       Denmark             9.22

In [51]:
# how many total regions are there
df['region'].unique().shape[0] # my method
df['region'].value_counts().count()

np.int64(22)

In [61]:
df['region']

0           Southern Asia
1         Southern Europe
2         Northern Africa
3         Southern Europe
4           Middle Africa
              ...
189    South-Eastern Asia
190          Western Asia
191          Western Asia
192        Eastern Africa
193        Eastern Africa
Name: region, Length: 194, dtype: object

In [78]:
# how many countries lie i eastern europe region 
int(df['region'].value_counts()['Eastern Europe'])
#countries in eastern europe
df[df['region']=='Eastern Europe'][['country']]

             country
14           Belarus
24          Bulgaria
43    Czech Republic
73           Hungary
111          Moldova
136           Poland
139          Romania
140           Russia
151  Slovak Republic
181          Ukraine

In [87]:
# who is the political leader of the second highest pupulated countrt
df.sort_values(by='population',ascending=False).head(2).tail(1)[['country','political_leader']]

   country political_leader
34   China       Xi Jinping

In [104]:
# how many countries are there whose political leaders are unknown 
df[df['political_leader'].isna() ==True][['country']]

                            country
27                       Cabo Verde
151                 Slovak Republic
159             St. Kitts and Nevis
160                       St. Lucia
161  St. Vincent and the Grenadines
172                     Timor-Leste
190              West Bank and Gaza

In [114]:
# how many countrues have Republic i their name 
def is_republic(name):
    if 'republic' in name.lower():
        return True
count=0
for i in df['country_long'] :
    if is_republic(i) :
        count+=1
print(count)

125

In [119]:
# which country in the africa region has the highest population
df[df['continent']=='Africa'].sort_values(by='population',ascending=False).head(1)[['country','population']]

     country  population
125  Nigeria   218541212